steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/godave/github.com/4dave/godave:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/godave/github.com/4dave/godave:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'godave', '--region=us-central1', '--platform=managed', '--image=gcr.io/godave/github.com/4dave/godave:$SHORT_SHA']
